src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @UniqueEntity(fields={"start_at","end_at"})
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_at;

    /**
     * @Assert\GreaterThanOrEqual(propertyPath="start_at")
     * @ORM\Column(type="datetime")
     */
    private $end_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAborted = false;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="events")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Professional::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     */
    private $professional;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reason;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $validatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isFree = true;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modifiedAt;

    public function __construct()
    {
        $this->modifiedAt = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getIsAborted(): ?bool
    {
        return $this->isAborted;
    }

    public function setIsAborted(bool $isAborted): self
    {
        $this->isAborted = $isAborted;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getProfessional(): ?Professional
    {
        return $this->professional;
    }

    public function setProfessional(?Professional $professional): self
    {
        $this->professional = $professional;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(?string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getValidatedAt(): ?\DateTimeInterface
    {
        return $this->validatedAt;
    }

    public function setValidatedAt(?\DateTimeInterface $validatedAt): self
    {
        $this->validatedAt = $validatedAt;

        return $this;
    }

    public function getIsFree(): ?bool
    {
        return $this->isFree;
    }

    public function setIsFree(bool $isFree): self
    {
        $this->isFree = $isFree;

        return $this;
    }

    /**
     * This method can be used when Client wants to cancel this event
     * or on unsubscribe moment.
     *
     * @return bool true annulation or no problem
     *              false not annulable and user must pay
     *
     * @throws Exception
     */
    public function isAnnulable()
    {
        $today = new DateTime('now', new \DateTimeZone('Europe/Berlin'));
        $interval = $this->getEndAt()->diff($today);

        return !$this->getValidatedAt() || !$interval->invert || ($interval->invert && $interval->d > 1);
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(?\DateTimeInterface $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }
}

src/Entity/Professional.php
<?php

namespace App\Entity;

use App\Repository\ProfessionalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProfessionalRepository::class)
 */
class Professional extends Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @Assert\Length(min=14, max=14)
     * @ORM\Column(type="string", length=14)
     */
    private $siret;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $googleId;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActif;

    /**
     * @ORM\ManyToMany(targetEntity=Address::class, mappedBy="professionals")
     */
    private $addresses;

    /**
     * @ORM\OneToMany(targetEntity=Planning::class, mappedBy="professional", orphanRemoval=true)
     */
    private $plannings;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="professional", orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\ManyToMany(targetEntity=Domaine::class, mappedBy="professionals")
     */
    private $domaines;

    /**
     * @ORM\ManyToMany(targetEntity=Experience::class, mappedBy="professionals")
     */
    private $experiences;

    /**
     * @ORM\ManyToMany(targetEntity=Holiday::class, mappedBy="professionals")
     */
    private $holidays;

    /**
     * @ORM\ManyToMany(targetEntity=Diploma::class, mappedBy="professionals")
     */
    private $diplomas;

    /**
     * @ORM\ManyToOne(targetEntity=Plan::class, inversedBy="Professionnals")
     */
    private $plan;

    /**
     * @Gedmo\Slug(fields={"id", "siret"})
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerId;

    /**
     * @ORM\OneToMany(targetEntity=PaymentMethod::class, mappedBy="professional", orphanRemoval=true)
     */
    private $paymentMethods;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subscriptionStripeId;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="professional", orphanRemoval=true)
     */
    private $events;

    public function __construct()
    {
        parent::__construct();
        $this->addresses = new ArrayCollection();
        $this->plannings = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->domaines = new ArrayCollection();
        $this->experiences = new ArrayCollection();
        $this->holidays = new ArrayCollection();
        $this->diplomas = new ArrayCollection();
        $this->paymentMethods = new ArrayCollection();
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }

    public function getIsActif(): ?bool
    {
        return $this->isActif;
    }

    public function setIsActif(bool $isActif): self
    {
        $this->isActif = $isActif;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->addProfessional($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            $address->removeProfessional($this);
        }

        return $this;
    }

    /**
     * @return Collection|Planning[]
     */
    public function getPlannings(): Collection
    {
        return $this->plannings;
    }

    public function getPlanningsIntDayList()
    {
        $businessHours = [];
        /** @var Planning $planning */
        foreach ($this->plannings as $planning) {
            $start = $planning->getStartPmAt() ?? $planning->getStartAmAt();
            $end = $planning->getEndAmAt() ?? $planning->getEndPmAt();
            $businessHours[] = [
                'daysOfWeek' => $planning->getDay(), // Monday, Tuesday, Wednesday
                'startTime' => $planning->getStartPmAt()->format('H:i'), // 8am
                'endTime' => $planning->getEndPmAt()->format('H:i'), // 6pm
            ];
            $businessHours[] = [
                'daysOfWeek' => $planning->getDay(), // Monday, Tuesday, Wednesday
                'startTime' => $planning->getStartAmAt()->format('H:i'), // 8am
                'endTime' => $planning->getEndAmAt()->format('H:i'), // 6pm
            ];
        }

        return json_encode($businessHours);
    }

    public function addPlanning(Planning $planning): self
    {
        if (!$this->plannings->contains($planning)) {
            $this->plannings[] = $planning;
            $planning->setProfessional($this);
        }

        return $this;
    }

    public function removePlanning(Planning $planning): self
    {
        if ($this->plannings->removeElement($planning)) {
            // set the owning side to null (unless already changed)
            if ($planning->getProfessional() === $this) {
                $planning->setProfessional(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setProfessional($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getProfessional() === $this) {
                $contact->setProfessional(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Domaine[]
     */
    public function getDomaines(): Collection
    {
        return $this->domaines;
    }

    public function addDomaine(Domaine $domaine): self
    {
        if (!$this->domaines->contains($domaine)) {
            $this->domaines[] = $domaine;
            $domaine->addProfessional($this);
        }

        return $this;
    }

    public function removeDomaine(Domaine $domaine): self
    {
        if ($this->domaines->removeElement($domaine)) {
            $domaine->removeProfessional($this);
        }

        return $this;
    }

    /**
     * @return Collection|Experience[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->addProfessional($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): self
    {
        if ($this->experiences->removeElement($experience)) {
            $experience->removeProfessional($this);
        }

        return $this;
    }

    /**
     * @return Collection|Holiday[]
     */
    public function getHolidays(): Collection
    {
        return $this->holidays;
    }

    public function addHoliday(Holiday $holiday): self
    {
        if (!$this->holidays->contains($holiday)) {
            $this->holidays[] = $holiday;
            $holiday->addProfessional($this);
        }

        return $this;
    }

    public function removeHoliday(Holiday $holiday): self
    {
        if ($this->holidays->removeElement($holiday)) {
            $holiday->removeProfessional($this);
        }

        return $this;
    }

    /**
     * @return Collection|Diploma[]
     */
    public function getDiplomas(): Collection
    {
        return $this->diplomas;
    }

    public function addDiploma(Diploma $diploma): self
    {
        if (!$this->diplomas->contains($diploma)) {
            $this->diplomas[] = $diploma;
            $diploma->addProfessional($this);
        }

        return $this;
    }

    public function removeDiploma(Diploma $diploma): self
    {
        if ($this->diplomas->removeElement($diploma)) {
            $diploma->removeProfessional($this);
        }

        return $this;
    }

    public function getPlan(): ?Plan
    {
        return $this->plan;
    }

    public function setPlan(?Plan $plan): self
    {
        $this->plan = $plan;

        return $this;
    }

    public function getCustomerId(): ?string
    {
        return $this->customerId;
    }

    public function setCustomerId(?string $customerId): self
    {
        $this->customerId = $customerId;

        return $this;
    }

    /**

src/Controller/Professional/DiplomaController.php
<?php

namespace App\Controller\Professional;

use App\Entity\Diploma;
use App\Form\DiplomaType;
use App\Repository\DiplomaRepository as DiplomaRepo;
use App\Repository\ProfessionalRepository as ProfRepo;
use Doctrine\ORM\EntityManagerInterface as Em;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/professional/diploma", name="professional_diploma")
 * Class DiplomaController
 */
class DiplomaController extends AbstractController
{
    private TranslatorInterface $translator;
    private DiplomaRepo $repository;
    private ProfRepo $professionalRepository;
    private Em $manager;

    public function __construct(TranslatorInterface $translator, DiplomaRepo $repository, ProfRepo $profRepo, Em $em)
    {
        $this->translator = $translator;
        $this->repository = $repository;
        $this->professionalRepository = $profRepo;
        $this->manager = $em;
    }

    /**
     * @Route("/new", name="_new", methods={"GET", "POST"})
     * @Route("/{id}/edit", name="_edit", methods={"GET", "POST"})
     */
    public function new(Diploma $Diploma = null, Request $request)
    {
        $button = $this->translator->trans('Edit');
        $message = $this->translator->trans('Diploma was edited successfully');
        if (!$Diploma) {
            $Diploma = new Diploma();
            $button = $this->translator->trans('Save');
            $message = $this->translator->trans('Diploma was created successfully');
        }

        $form = $this->createForm(DiplomaType::class, $Diploma);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ('Save' === $button) {
                $prof = $this->getUser()->getClient();
                $Diploma->addProfessional($prof);
                $this->manager->persist($Diploma);
            }

            $this->manager->flush();
            $this->addFlash('success', $message);

            return $this->redirectToRoute('professional_profile');
        }
        $view = 'professional/diploma/register_notify.html.twig';

        return $this->render($view, ['form' => $form->createView(), 'button' => $button]);
    }

    /**
     * @Route("/{id}/delete", name="_delete", methods={"DELETE"})
     *
     * @return RedirectResponse
     */
    public function delete(Diploma $Diploma, Request $request)
    {
        $message = $this->translator->trans('Delete Diploma failed');
        $key = 'error';
        if ($this->isCsrfTokenValid('delete'.$Diploma->getId(), $request->get('_token'))) {
            $this->manager->remove($Diploma);
            $this->manager->flush();
            $key = 'success';
            $message = $this->translator->trans('Diploma deleted successfully');
        }

        $this->addFlash($key, $message);

        return $this->redirectToRoute('professional_profile');
    }
}

templates/professional/event/_delete.html.twig
<form method="post" action="{{ path('professional_event_delete', {'id': event.id }) }}"
      onsubmit="return confirm('Are you sure you want Delete this event?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete') }}">
    <input type="hidden" name="_method" value="delete">
    <button class="btn btn-outline-danger">{% trans %}Delete{% endtrans %}</button>
</form>

templates/professional/event/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Profile{% endtrans %}{% endblock %}

{% block body %}

    <div class="container mt-5  pt-5">
        {% for flashError in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">{{ flashError }}</div>
        {% endfor %}
        {% for flashError in app.flashes('success') %}
            <div class="alert alert-success" role="alert">{{ flashError }}</div>
        {% endfor %}

        <h1 class="text-center text-primary">{% trans %}Cancel this Event{% endtrans %}</h1>

        <div class="profile">
            <h4>{% trans %}Give us some justification, please.{% endtrans %}
            {% if isPro is defined %}
                <form action="{{ path('professional_event_cancel', {'id': event.id}) }}" method="post">
            {% elseif isClient is defined %}
                <form action="{{ path('client_event_cancel', {'id': event.id}) }}" method="post">
            {% endif %}
                    <textarea class="form-control" name="reason" id="reason" cols="30" rows="4" placeholder="Because, I will be absent" required></textarea>
                <div class="d-flex flex-row">
                    <button class="btn btn-success">{% trans %}Validate{% endtrans %}</button>
                    <a href="{{ path('professional_event_index') }}"
                       class="btn btn-outline-dark">{% trans %}Back to Events list{% endtrans %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/professional/event/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Profile{% endtrans %}{% endblock %}

{% block body %}

    <div class="container mt-5  pt-5">
        {% for flashError in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">{{ flashError }}</div>
        {% endfor %}
        {% for flashError in app.flashes('success') %}
            <div class="alert alert-success" role="alert">{{ flashError }}</div>
        {% endfor %}

        <h1 class="text-center text-primary">{% trans %}Welcome on your profile{% endtrans %}</h1>

        <div class="profile">
            <ul class="list-group">

                <div class="row">
                    <div class="col col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <p class="card-title">{{ event.title }}</p>
                                <p>{% trans %}Date{% endtrans %} : {{ event.startAt | date("d-m-Y h:ia") }} - {{ event.endAt | date("d-m-Y h:ia") }}</p>
                                <p>{% trans %}Professional{% endtrans %} : {{ event.professional.name | upper}} {{ event.professional.lastname | capitalize }}</p>
                                <p>{% trans %}Client{% endtrans %} :
                                    {% if event.client %}
                                        {{ event.client.name | upper}} {{ event.client.lastname | capitalize }}
                                    {% else %}
                                        {% trans %}No Client found{% endtrans %}
                                    {% endif %}
                                </p>
                                <p class="card-title">{{ event.description }}</p>
                                <div class="d-flex flex-row">
                                    {% if not event.validatedAt %}
                                        <a href="{{ path('professional_event_validate', {'id': event.id }) }}" class="btn btn-primary">{% trans %}Validate{% endtrans %}</a>
                                    {% endif %}
                                    <a href="{{ path('professional_event_cancel', {'id': event.id }) }}" class="btn btn-warning">{% trans %}Cancel{% endtrans %}</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </ul>
        </div>
    </div>
{% endblock %}

templates/professional/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Profile{% endtrans %}{% endblock %}

{% block body %}

    <div class="container mt-5  pt-5">
        {% for flashError in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">{{ flashError }}</div>
        {% endfor %}
        {% for flashError in app.flashes('success') %}
            <div class="alert alert-success" role="alert">{{ flashError }}</div>
        {% endfor %}

        <h1 class="text-center text-primary">{% trans %}Welcome on your profile{% endtrans %}</h1>

        <div class="profile">
            <ul class="list-group">

                <div class="row">
                    <div class="col col-md-4">
                        <h2 class="text-center text-primary">{% trans %}Appointments{% endtrans %}</h2>
                        {% for event in events %}
                            {% if not event.isAborted and event.client %}
                                <div class="card">
                                    <div class="card-body">
                                        <p class="card-title">{{ event.description }}</p>
                                        <p>{% trans %}Date{% endtrans %} : {{ event.startAt | date("d-m-Y h:ia") }} - {{ event.endAt | date("d-m-Y h:ia") }}</p>
                                        <p>{% trans %}Professional{% endtrans %} : {{ event.professional.name | upper}} {{ event.professional.lastname | capitalize }}</p>
                                        <p>{% trans %}Client{% endtrans %} : {{ event.client.name | upper}} {{ event.client.lastname | capitalize }}</p>
                                        <div class="d-flex flex-row">
                                            <a href="{{ path('professional_event_details', {'id': event.id }) }}" class="btn btn-primary">{% trans %}View details{% endtrans %}</a>
                                            <a href="{{ path('professional_event_cancel', {'id': event.id }) }}" class="btn btn-warning">{% trans %}Cancel{% endtrans %}</a>
                                        </div>
                                    </div>
                                </div>
                            {% elseif event.isAborted and event.professional %}
                                <div class="card bg-warning">
                                    <div class="card-body">
                                        <p class="card-title">{{ event.description }}</p>
                                        <p>{% trans %}Date{% endtrans %} : {{ event.startAt | date("d-m-Y h:ia") }} - {{ event.endAt | date("d-m-Y h:ia") }}</p>
                                        <p>{% trans %}Professional{% endtrans %} : {{ event.professional.name | upper}} {{ event.professional.lastname | capitalize }}</p>
                                        <p>{% trans %}Details{% endtrans %} :
                                            {{ event.reason }}
                                        </p>
                                        <div class="d-flex flex-row">
                                            <a href="{{ path('professional_event_details', {'id': event.id }) }}" class="btn btn-primary">{% trans %}View details{% endtrans %}</a>
                                            <form action="{{ path('professional_event_restaure', {'id': event.id}) }}" method="post">
                                                <button type="submit" class="btn btn-outline-success">Restaure</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% else %}
                            <p>{% trans %}No Event found.{% endtrans %}</p>
                        {% endfor %}
                    </div>

                    <div class="col col-md-8">
                        <input type="hidden" id="events_js" name="events_js" value="{{ eventsFC }}">
                        <div id="fullCalendar_js"
                             data-planning='{{ professional.planningsIntDayList|raw }}'
                        ></div>
                    </div>
                </div>
            </ul>

        </div>
    </div>

    <!--MODAL ADD EVENT-->
    <div class="add-event">
        <!-- Modal -->
        <div class="modal fade" id="appointment" tabindex="-1" aria-labelledby="appointmentModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form id="form_js" action="" method="post">
                        <!--HEADER-->
                        <div class="modal-header">
                            <h5 class="modal-title" id="appointmentModalLabel">{% trans %}Having appointment{% endtrans %}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <!--BODY-->
                        <div class="modal-body">
                            <div class="form-group">
                                <input class="form-control" type="text" id="title" name="title" placeholder="Très urgent">
                            </div>
                            <div class="input-group">
                                <input class="form-control" type="date" id="startAt" name="startAt">
                                <input class="form-control" type="time" id="startAtTime" name="startAtTime">
                            </div>
                            <div class="input-group">
                                <input class="form-control" type="date" id="endAt" name="endAt">
                                <input class="form-control" type="time" id="endAtTime" name="endAtTime">
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="checkbox" id="isAborted" name="isAborted">
                            </div>
                            <div class="form-group">
                                <textarea name="description" id="description" cols="30" rows="4" placeholder="Description"></textarea>
                            </div>
                        </div>

                        <!--BUTTONS-->
                        <div class="modal-footer">
                            <form method="post" id="event_delete_js" action="{{ path('professional_event_delete', {'id':'-1'}) }}"
                                  onsubmit="return confirm('Are you sure you want Delete this Event?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ professional.slug) }}">
                                <button class="btn btn-outline-danger" id="event_delete_btn_js" >{% trans %}Delete{% endtrans %}</button>
                            </form>

                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans %}Close{% endtrans %}</button>
                            <button type="submit" class="btn btn-primary">{% trans %}Save{% endtrans %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('fullCalendar') }}
{% endblock %}

templates/professional/event/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="container">
        <h1 class="text-primary text-center mt-5 pt-5">
            {% if button == "Save" %}
                {% trans %}Edit Event{% endtrans %}
            {% else %}
                {% trans %}Create a new Event{% endtrans %}
            {% endif %}
        </h1>

        {{ form_start(form) }}
        <div class="row">
            <div class="col col-md-6">
                {{ form_rest(form) }}
            </div>
            <div class="col col-md-6">
                {% if event.isAborted %}
                    <h4>{% trans %}Reason, why this appointment was Canceled{% endtrans %}</h4>
                    <p>{{ event.reason }}</p>
                {% endif %}
            </div>
            <div class="col col-12 d-flex flex-row">
                <button type="submit" class="btn btn-success">{{ button }}</button>
                <a href="{{ path('client_profile') }}" class="btn btn-secondary">{% trans %}Back to Profile{% endtrans %}</a>
            </div>
        </div>
        {{ form_end(form) }}
        {% include "event/_delete.html.twig" %}
    </section>
{% endblock %}

{% block title %}
    {% if button == "Save" %}
        {% trans %}Edit Event{% endtrans %}
    {% else %}
        {% trans %}Create a new Event{% endtrans %}
    {% endif %}
{% endblock %}